Arch:
  name: clusternet5gTwoHead
  num_channel: 2
  num_sub_heads: 5
  output_k_A: 70
  output_k_B: 10
DataLoader:
  batch_size: 150
  num_workers: 16
  shuffle: true
Optim:
  lr: 0.0001
  name: Adam
Scheduler:
  gamma: 0.75
  milestones:
  - 10
  - 20
  - 30
  - 50
  - 70
  name: MultiStepLR
Trainer:
  device: cuda
  head_control_params:
    A: 2
    B: 1
  max_epoch: 1000
  name: iicgeo
  save_dir: baseline/cifar/iicgeo
  use_sobel: true
